# Generated by Django 3.0.5 on 2020-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200423_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
