# Generated by Django 3.0.5 on 2020-04-24 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='preamble',
            field=ckeditor.fields.RichTextField(blank=True, default='/%Y/%m/%d', null=True),
        ),
    ]
